<?php
/**
 * @var ecollect\Core\Block\CustomTicket\Success $block
 */
$order = $this->getOrder();
$total = $this->getTotal();
$payment = $this->getPayment();

$link_to_order = __(
    'Your order %1 has been successfully generated.',
    '<a href="' . $block->escapeUrl($this->getOrderUrl()) . '">' . $block->escapeHtml($order->getIncrementId()) . '</a>'
);

$payment_method = $this->getPaymentMethod();
$info_payment = $this->getInfoPayment();
?>

<div id="box-ecollect">

    <?php if ($payment_method == 'ecollect_customticket'): ?>
        <h2 class="ecollect-title"><?php /* @escapeNotVerified */ echo __('Thank you for your purchase!'); ?></h2>

        <p>
            <?php /* @escapeNotVerified */ echo $link_to_order; ?>
        </p>

        <p>
            <?php echo 'Generate the ticket and pay it wherever you want.'; ?>
        </p><p>
            <?php /* @escapeNotVerified */ echo __('Will be approved within 2 business days.'); ?>
        </p>
        <a href="<?php echo $block->escapeUrl(urldecode($payment->getAdditionalInformation('activation_uri'))); ?>"
           target="_blank" id="btn-boleto-ecollect">
            <?php /* @escapeNotVerified */ echo __('Generate Ticket'); ?>
        </a>

    <?php endif; ?>

</div>

<div id="logo-ecollect">
    <!--img src="https://secure.mlstatic.com/components/resources/mp/desktop/css/assets/desktop-logo-ecollect.png"/-->
</div>

<div class="primary button-success">
    <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
</div>
